# renew_before_expiry = 30 days
version = 2.9.0
archive_dir = /etc/letsencrypt/archive/course.uportal.uz
cert = /etc/letsencrypt/live/course.uportal.uz/cert.pem
privkey = /etc/letsencrypt/live/course.uportal.uz/privkey.pem
chain = /etc/letsencrypt/live/course.uportal.uz/chain.pem
fullchain = /etc/letsencrypt/live/course.uportal.uz/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = df77418eea5f6057e280b18fbfdb87ba
authenticator = nginx
installer = nginx
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
